# Generated by Django 4.1.3 on 2023-03-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1.Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '2.Product'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': 'Sizes'},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
